# Generated by Django 5.2.4 on 2025-07-30 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo_pacote', models.CharField(max_length=50)),
                ('quantidade_pacote', models.PositiveIntegerField()),
                ('quantidade_pacote_restante', models.PositiveIntegerField()),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.cliente')),
            ],
        ),
    ]
