# Generated by Django 5.2.4 on 2025-07-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presença', models.BooleanField(default=False, help_text='Marque se o cliente compareceu')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.agenda')),
            ],
        ),
    ]
