# Generated by Django 5.2.4 on 2025-07-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0002_painel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painel',
            old_name='presença',
            new_name='presenca',
        ),
    ]
